spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socce_store
    username: postgres
    password: CODERJAVA
    driver-class-name: org.postgresql.Driver
  liquibase:
      change-log: db/changelog/main-changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
